services:
  - type: web
    name: backend-bookmarks
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nome-do-seu-banco-na-neon
          property: connectionString
